### ISSUE TITLE
Create standard for pulling data from Firebase into C++

### ISSUE THREAD

**Issue by jack-margeson** [EECE3093C/team-project-green-software#18]
This ticket includes:
- Creating and documenting a standard (having a defined and smart data type) that pulls data from Firebase into our C++ software program.
- Pulling test data (see https://github.com/EECE3093C/team-project-green/issues/26) in order to test this method/way of storing data in memory locally

This ticket does not include:
- Anything to do with the hardware implementation of data transfer. This "other half" to our data flow will be handled in https://github.com/EECE3093C/team-project-green-arduino/issues/7.

**Comment by Bocklavich** [comment]
Below is an example of the object that would be created when pulling data from our firebase.
```mermaid
classDiagram

class plant_data
plant_data : +string name
plant_data : +int moisture_level
plant_data : +set_new_moisture()




```
