### ISSUE TITLE
Create unit tests for C++ software

### ISSUE THREAD

**Issue by jack-margeson** [EECE3093C/team-project-green-software#19]
This ticket includes:
- Writing software tests for the C++ plant monitoring software for reliability 
- Tests for the methods that get/pull information down from Firebase (see #18)
- Tests for the methods used for querying API (see #16 )
- Tests for the methods used for searching plants (see #17)

This ticket does not include:
- Uploading/hosting these tests on the GitHub Actions for the software repository (planned for Iteration 4)

**Comment by hellcatf6** [comment]
Unit test framework completed. closing issue.
