### ISSUE TITLE
Refine data being returned from the API

### ISSUE THREAD

**Issue by jack-margeson** [EECE3093C/team-project-green-software#58]
This ticket includes:
- Looking at the API call that we're making to the plant database and making sure that we're getting the data we need/want
- "What other fields of information could be useful for our project?" and adding queries in order to get those values out of the JSON object 
- Adding those newly pulled data points as member variables in the Plant class, setting them properly 

This ticket does not include:
- Additional API work (all API calling/JSON parsing already done in #16 )

**Comment by Bocklavich** [comment]
While working on #60 , MJ created a different method for finding moisture values as a direct piece of data was direct populated piece of data was not accessible in the API but other information such as location was used to guess moisture level needed for a plant species.
