### ISSUE TITLE
Pull down Arduino-provided values from Firebase into C++

### ISSUE THREAD

**Issue by jack-margeson** [EECE3093C/team-project-green-software#59]
This ticket includes:
- Creating a C++ module and method that queries the Firebase on call 
- Method returns current soil moisture data 

This ticket does not include: 
- Incorporating this method into the view plant menu

**Comment by Bocklavich** [comment]
There are two options to for pulling data from Firebase into C++. One is to pull a single value on command, and another is to use a listener class. 
Single Pull:
Advantages
- on function run, pull current moisture value as a single variable
- simple and familiar coding
Disadvantages
-Needs to be updated constantly
Listener Class:
Advantages
-Possibly won't need to run a function every time to retrieve the value
Disadvantages:
-Have to implement an entire class

**Comment by Bocklavich** [comment]
Commit #85 populates a function to pull values from firebase into C++.
