### ISSUE TITLE
Create watering comparison method

### ISSUE THREAD

**Issue by jack-margeson** [EECE3093C/team-project-green-software#60]
This ticket includes:
- Figuring out which variable returned from the API we want our watering comparison to be based off of
- Creating a method that maps a current water value to a range of values determined from the API information

**Comment by jack-margeson** [comment]
Notes from Hunter: min/max precip, growth form are potential candidates.

**Comment by MJ-Schnee** [comment]
I looked into the API and discovered that not many plants have the min/max precipitation values or any values related to how much moisture is required for them. After discussing with the team, we decided that we should create a map of countries to the average moisture levels required for plants in those regions and will compare the plants current moisture levels with those.
