### ISSUE TITLE
Create GitHub action for C++ Docker images

### ISSUE THREAD

**Issue by hellcatf6** [EECE3093C/team-project-green-software#8]
Explore GitHub actions that apply to our C++ Docker image. Including testing if the Docker file runs without errors.

**Comment by jack-margeson** [comment]
Note that this ticket does not include creating GitHub Actions for unit tests, _only_ actions related to Docker. There's a planned ticket for Iteration 4 to create GitHub Actions for unit tests (which are being created in #19)

**Comment by hellcatf6** [comment]
Was able to make a Github action that builds are Docker image on each pull request. This was chosen so if any changes were made to the code the Docker image would rebuild to remain current. This also insures our image builds successfully after any new changes are made.
